const DATA = [
  {
    "societe": "Ouest France",
    "rue": "31 rue Larcher ",
    "cp": 14400,
    "ville": "Bayeux",
    "latitude": 49.2757,
    "longitude": -0.701957,
    "typeBatiment": "Rédaction",
    "photoBatiment": "",
    "logo": '..\images\ouest_france.png',
    "groupeParent": "Ouest-France",
    "nom": "BALLARD",
    "prenom": "Guillaume",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "14 place Pierre Bouchard",
    "cp": 14000,
    "ville": "Caen",
    "latitude": 49.1835,
    "longitude": -0.36422,
    "typeBatiment": "Rédaction",
    "photoBatiment": "",
    "groupeparent": "Ouest-France",
    "logo": "..\images\ouest_france.png",
    "groupeParent": "Ouest-France",
    "nom": "BALLARD",
    "prenom": "Guillaume"?
    "photo": "",
    "description": ""
  },
  {
    
    "societe": "Ouest France",
    "rue": "3, rue de la Trinité",
    "cp": 14700,
    "ville": "Falaise",
    "latitude": 48.9182,
    "longitude": -0.2119,
    "typeBatiment": "Rédaction",
    "photoBatiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeParent": "Ouest-France",
    "nom": "BALLARD",
    "prenom": "Guillaume",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "27 rue Pont Mortain",
    "cp": 14100,
    "ville": "Lisieux",
    "latitude": "49.1439556",
    "longitude": "0.2266404",
    "typeBatiment": "Rédaction",
    "photoBatiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeParent": "Ouest-France",
    "nom": "BALLARD",
    "prenom": "Guillaume",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "16 Bd Fernand Moureaux",
    "cp": 14360,
    "ville": "Trouville",
    "latitude": "49.3640512",
    "longitude": "0.0831731",
    "typeBatiment": "Rédaction",
    "photoBatiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeParent": "Ouest-France",
    "nom": "BALLARD",
    "prenom": "Guillaume",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "24 rue Chaussée",
    "cp": 14500,
    "ville": "Vire",
    "latitude": "48.8377716",
    "longitude": "-0.8903022",
    "typeBatiment": "Rédaction",
    "photoBatiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeParent": "Ouest-France",
    "nom": "BALLARD",
    "prenom": "Guillaume",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "9, place Duclos",
    "cp": 22100,
    "ville": "Dinan",
    "latitude": "48.453731",
    "longitude": "-2.047911",
    "typeBatiment": "Rédaction",
    "photoBatiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeParent": "Ouest-France",
    "nom": "BIGORGNE",
    "prenom": "Joël",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "4 rue de la Pompe",
    "cp": 22200,
    "ville": "Guingamp",
    "latitude": "48.5634349",
    "longitude": "-3.1518538",
    "typeBatiment": "Rédaction",
    "photoBatiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeParent": "Ouest-France",
    "nom": "BIGORGNE",
    "prenom": "Joël",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "19 rue du Val ",
    "cp": 22400,
    "ville": "Lamballe",
    "latitude": "48.4693025",
    "longitude": "-2.5139728",
    "typeBatiment": "Rédaction",
    "photoBatiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeParent": "Ouest-France",
    "nom": "BIGORGNE",
    "prenom": "Joël",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "1 rue de Viarmes",
    "cp": 22300,
    "ville": "Lannion",
    "latitude": "48.734702",
    "longitude": "-3.463987",
    "typeBatiment": "Rédaction",
    "photoBatiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeParent": "Ouest-France",
    "nom": "BIGORGNE",
    "prenom": "Joël",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "6 rue Saint-Joseph",
    "cp": 22600,
    "ville": "Loudéac",
    "latitude": "48.177916",
    "longitude": "-2.754989",
    "typeBatiment": "Rédaction",
    "photoBatiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "BIGORGNE",
    "prenom": "Joël",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "1 rue de l'Yser",
    "cp": 22500,
    "ville": "Paimpol",
    "latitude": "48.779867",
    "longitude": "-3.042711",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "BIGORGNE",
    "prenom": "Joël",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "23 rue Jouallan",
    "cp": 22000,
    "ville": "Saint Brieuc",
    "latitude": "48.513268",
    "longitude": "-2.760881",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "\"",
    "nom": "BIGORGNE",
    "prenom": "Joël",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "24 rue Algésiras",
    "cp": 29275,
    "ville": "Brest",
    "latitude": "48.390146",
    "longitude": "-4.489603",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "GOUÉROU",
    "prenom": "Christian",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "11 place de la Mairie",
    "cp": 29270,
    "ville": "Carhaix",
    "latitude": "48.276000",
    "longitude": "-3.573684",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "GOUÉROU",
    "prenom": "Christian",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "10 av. du Dr Nicolas",
    "cp": 29900,
    "ville": "Concarneau",
    "latitude": "47.870129",
    "longitude": "-3.917293",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "GOUÉROU",
    "prenom": "Christian",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "45 rue Camille Réaud",
    "cp": 29100,
    "ville": "Douarnenez",
    "latitude": "48.095167",
    "longitude": "-4.334907",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "GOUÉROU",
    "prenom": "Christian",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "26 rue d'Aiguillon",
    "cp": 29600,
    "ville": "Morlaix",
    "latitude": "48.576557",
    "longitude": "-3.825213",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "GOUÉROU",
    "prenom": "Christian",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "24 Bd Dupleix",
    "cp": 29101,
    "ville": "Quimper",
    "latitude": "47.994757",
    "longitude": "-4.100569",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "GOUÉROU",
    "prenom": "Christian",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "12 rue Génot",
    "cp": 29300,
    "ville": "Quimperlé",
    "latitude": "47.872129",
    "longitude": "-3.548521",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "GOUÉROU",
    "prenom": "Christian",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "10 rue du Breil",
    "cp": 35051,
    "ville": "Rennes",
    "latitude": "48.0951667",
    "longitude": "-1.6291111111111112",
    "typeBatiment": "Siège social - Rédaction -Imprimerie",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "ECHELARD",
    "prenom": "Louis",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "16 rue de la Forêt",
    "cp": 35305,
    "ville": "Fougères",
    "latitude": "48.355636",
    "longitude": "-1.200501",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "JARNIGON",
    "prenom": "Vincent",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "14 C rue de la Gare",
    "cp": 35600,
    "ville": "Redon",
    "latitude": "47.652244",
    "longitude": "-2.086772",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "\"",
    "nom": "JARNIGON",
    "prenom": "Vincent",
    "description": ""
  },
  {
    "societe": "SIGL",
    "rue": "38 rue du Pré-Botté",
    "cp": 35051,
    "ville": "Rennes",
    "latitude": "48.109316",
    "longitude": "-1.677048",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "groupeparent": "Ouest-France",
    "nom": "JARNIGON",
    "prenom": "Vincent",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "15 rue Jean Jaurès",
    "cp": 35409,
    "ville": "Saint Malo",
    "latitude": "48.648545",
    "longitude": "-2.007195",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "JARNIGON",
    "prenom": "Vincent",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "36 Bd de Châteaubriant",
    "cp": 35500,
    "ville": "Vitré",
    "latitude": "48.118539",
    "longitude": "-1.210328",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "JARNIGON",
    "prenom": "Vincent",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "66 place Foch",
    "cp": 44151,
    "ville": "Ancenis",
    "latitude": "47.365768",
    "longitude": "-1.176898",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "WAJDZIK",
    "prenom": "Arnaud",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "9 rue Michel Grimaud",
    "cp": 44110,
    "ville": "Chateaubriant",
    "latitude": "47.717335",
    "longitude": "-1.376247",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "WAJDZIK",
    "prenom": "Arnaud",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "4 Bd Hennecart",
    "cp": 44500,
    "ville": "La Baule",
    "latitude": "47.281968",
    "longitude": "-2.393672",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "WAJDZIK",
    "prenom": "Arnaud",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "2 quai François Mitterand",
    "cp": 44203,
    "ville": "Nantes",
    "latitude": "47.207107",
    "longitude": "-1.555592",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "WAJDZIK",
    "prenom": "Arnaud",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "2 place Pierre Semard",
    "cp": 44600,
    "ville": "St Nazaire",
    "latitude": "47.285402",
    "longitude": "-2.210790",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "WAJDZIK",
    "prenom": "Arnaud",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "38  rue de la Guillauderie",
    "cp": 44118,
    "ville": "La Chevrolière",
    "latitude": "47.088760",
    "longitude": "-1.557485",
    "typeBatiment": "Imprimerie",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "MARTINAT",
    "prenom": "Renaud",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "5 bis, rue Thiers",
    "cp": 49051,
    "ville": "Angers",
    "latitude": "47.476179",
    "longitude": "-0.551948",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "GUERIN",
    "prenom": "Benoit",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "15 rue du Bourg Baudry",
    "cp": 49300,
    "ville": "Cholet",
    "latitude": "47.060960",
    "longitude": "-0.879535",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "GUERIN",
    "prenom": "Benoit",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "32 rue de la Constitution",
    "cp": 50305,
    "ville": "Avranches",
    "latitude": "48.684835",
    "longitude": "-1.360118",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "DENOYELLE",
    "prenom": "Nicolas",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "8 rue de l'ancien quai",
    "cp": 50100,
    "ville": "Cherbourg",
    "latitude": "49.637738",
    "longitude": "-1.624267",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "DENOYELLE",
    "prenom": "Nicolas",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "17 rue du Lycée",
    "cp": 50206,
    "ville": "Coutances",
    "latitude": "49.046299",
    "longitude": "-1.444208",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "DENOYELLE",
    "prenom": "Nicolas",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "92 rue Couraye",
    "cp": 50400,
    "ville": "Granville",
    "latitude": "48.837320",
    "longitude": "-1.592572",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "DENOYELLE",
    "prenom": "Nicolas",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "10 rue de la barque",
    "cp": 50003,
    "ville": "Saint-Lô",
    "latitude": "49.115246",
    "longitude": "-1.087461",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "DENOYELLE",
    "prenom": "Nicolas",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "42 Bis av Carnot",
    "cp": 53210,
    "ville": "Château-Gontier",
    "latitude": "47.827558",
    "longitude": "-0.708249",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "LE BLOA",
    "prenom": "Alan",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "92 av. Robert Buron",
    "cp": 53000,
    "ville": "Laval",
    "latitude": "48.075117",
    "longitude": "-0.761500",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "LE BLOA",
    "prenom": "Alan",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "Parvis Notre Dame",
    "cp": 53100,
    "ville": "Mayenne",
    "latitude": "48.304459",
    "longitude": "-0.618105",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "LE BLOA",
    "prenom": "Alan",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "20 rue des Quatre Vents",
    "cp": 56400,
    "ville": "Auray",
    "latitude": "47.666473",
    "longitude": "-2.985318",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "MARTEEL",
    "prenom": "Christel",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "55 rue du Port",
    "cp": 56100,
    "ville": "Lorient",
    "latitude": "47.747036",
    "longitude": "-3.360025",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "MARTEEL",
    "prenom": "Christel",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "1 Bis Bd des Carmes",
    "cp": 56800,
    "ville": "Ploërmel",
    "latitude": "47.932761",
    "longitude": "-2.401206",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "MARTEEL",
    "prenom": "Christel",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "21 rue Nationale",
    "cp": 56300,
    "ville": "Pontivy",
    "latitude": "48.067094",
    "longitude": "-2.965240",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "MARTEEL",
    "prenom": "Christel",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "15 rue de Closmadeuc",
    "cp": 56000,
    "ville": "Vannes",
    "latitude": "47.657554",
    "longitude": "-2.759666",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "MARTEEL",
    "prenom": "Christel",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "11, rue Saint Blaise",
    "cp": 61000,
    "ville": "Alençon",
    "latitude": "48.431447",
    "longitude": "0.089942",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "BRIONNE",
    "prenom": "Patrick",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "13, place Henri IV",
    "cp": 61200,
    "ville": "Argentan",
    "latitude": "48.744359",
    "longitude": "-0.020972",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "BRIONNE",
    "prenom": "Patrick",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "2 Rue Des rivières",
    "cp": 61100,
    "ville": "Flers",
    "latitude": "48.750170",
    "longitude": "-0.567517",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "BRIONNE",
    "prenom": "Patrick",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "13, rue du Marché au Blé",
    "cp": 72200,
    "ville": "La Flèche",
    "latitude": "47.700019",
    "longitude": "-0.073425",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "ROBIN",
    "prenom": "Claire",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "35, rue Gambetta",
    "cp": 72000,
    "ville": "Le Mans",
    "latitude": "48.005298",
    "longitude": "0.192975",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "ROBIN",
    "prenom": "Claire",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "11, rue Carnot",
    "cp": 72300,
    "ville": "Sablé sur Sarthe",
    "latitude": "47.841029",
    "longitude": "-0.334134",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "ROBIN",
    "prenom": "Claire",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "91, rue du Faubourg St Honoré",
    "cp": 75008,
    "ville": "Paris",
    "latitude": "48.871875",
    "longitude": "2.313111",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "VERNAY",
    "prenom": "Stéphane",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "26 place Kastler",
    "cp": 85300,
    "ville": "Challans",
    "latitude": "46.835170",
    "longitude": "-1.882886",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "BARDY",
    "prenom": "Céline",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "21 bis rue de la République",
    "cp": 85200,
    "ville": "Fontenay-Le-Comte",
    "latitude": "46.465678",
    "longitude": "-0.804319",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "BARDY",
    "prenom": "Céline",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "4 rue Raymond Poincaré",
    "cp": 85000,
    "ville": "La Roche-sur-Yon",
    "latitude": "46.669245",
    "longitude": "-1.433112",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "BARDY",
    "prenom": "Céline",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "7 place du Poilu de France",
    "cp": 85100,
    "ville": "Les Sables d'Olonne",
    "latitude": "46.496523",
    "longitude": "-1.783481",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "BARDY",
    "prenom": "Céline",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "17 Grande rue",
    "cp": 85500,
    "ville": "Les Herbiers",
    "latitude": "46.871553",
    "longitude": "-1.015613",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "BARDY",
    "prenom": "Céline",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France",
    "rue": "8, avenue Jean Cristau",
    "cp": 85800,
    "ville": "St Gilles Croix-de-vie",
    "latitude": "46.697946",
    "longitude": "-1.948253",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "logo": "..\images\ouest_france.png",
    "groupeparent": "Ouest-France",
    "nom": "BARDY",
    "prenom": "Céline",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Precom",
    "rue": "10, rue du Breil zone industrielle de Chantepie",
    "cp": 35200,
    "ville": "RENNES",
    "latitude": "48.0951667 ",
    "longitude": "-1.6291111111111112",
    "typeBatiment": "Siège",
    "photoBâtiment": "",
    "groupeparent": "Additi",
    "nom": "Lelièvre/Phillibert",
    "prenom": "Patrick/Christian",
    "photo": "",
    "description": ""
  },
  {
    "societe": " Régie Radio Régions",
    "rue": "10, rue du Breil zone industrielle de Chantepie",
    "cp": 35200,
    "ville": "RENNES",
    "latitude": "48.0951667 ",
    "longitude": "-1.6291111111111112",
    "typeBatiment": "Siège",
    "photoBâtiment": "",
    "groupeparent": "Additi",
    "nom": "Porcher",
    "prenom": "Laurent",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Medialex",
    "rue": "10, rue du Breil zone industrielle de Chantepie",
    "cp": 35200,
    "ville": "RENNES",
    "latitude": "48.0951667 ",
    "longitude": "-1.6291111111111112",
    "typeBatiment": "Siège",
    "photoBâtiment": "",
    "groupeparent": "Additi",
    "nom": "Colin",
    "prenom": "Olivier",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Happy Prod",
    "rue": "10, rue du Breil zone industrielle de Chantepie",
    "cp": 35200,
    "ville": "RENNES",
    "latitude": "48.0951667 ",
    "longitude": "-1.6291111111111112",
    "typeBatiment": "Siège",
    "photoBâtiment": "",
    "groupeparent": "Additi",
    "nom": "Connehaye",
    "prenom": "Romain",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Affiouest",
    "rue": "10, rue du Breil zone industrielle de Chantepie",
    "cp": 35200,
    "ville": "RENNES",
    "latitude": "48.0951667 ",
    "longitude": "-1.6291111111111112",
    "typeBatiment": "Siège",
    "photoBâtiment": "",
    "groupeparent": "Additi",
    "nom": "Le Bail",
    "prenom": "Remy",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Precontact",
    "rue": "10, rue du Breil zone industrielle de Chantepie",
    "cp": 35200,
    "ville": "RENNES",
    "latitude": "48.0951667 ",
    "longitude": "-1.6291111111111112",
    "typeBatiment": "Siège",
    "photoBâtiment": "",
    "groupeparent": "Additi",
    "nom": "Duru",
    "prenom": "Joël",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Ouest France Multimedia",
    "rue": "10, rue du Breil zone industrielle de Chantepie",
    "cp": 35200,
    "ville": "RENNES",
    "latitude": "48.0951667 ",
    "longitude": "-1.6291111111111112",
    "typeBatiment": "Siège",
    "photoBâtiment": "",
    "groupeparent": "Additi",
    "nom": "Philibert ",
    "prenom": "Christian",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Nantes Media",
    "rue": "10, rue du Breil zone industrielle de Chantepie",
    "cp": 35200,
    "ville": "RENNES",
    "latitude": "48.0951667 ",
    "longitude": "-1.6291111111111112",
    "typeBatiment": "Siège",
    "photoBâtiment": "",
    "groupeparent": "Additi",
    "nom": "Oger",
    "prenom": "Yann",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Dans nos cœurs",
    "rue": "10 rue du Breil zone industrielle de Chantepie",
    "cp": 35200,
    "ville": "RENNES",
    "latitude": "48.0951667 ",
    "longitude": "-1.6291111111111112",
    "typeBatiment": "Siège",
    "photoBâtiment": "",
    "groupeparent": "Additi",
    "nom": "Tricart",
    "prenom": "Anne-Sophie",
    "photo": "",
    "description": ""
  },
  {
    "societe": "Infomer",
    "rue": "13 rue du Breil",
    "cp": 35063,
    "ville": "Rennes",
    "latitude": "48.0956",
    "longitude": "-1.6269600000000537",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "groupeparent": "Ouest-France",
    "nom": "Boucher",
    "prenom": "Jean-Paul",
    "photo": "",
    "description": "Infomer est une filiale du groupe SIPA - Ouest-France, créée le 1er janvier 1990, spécialisée dans la presse maritime en France."
  },
  {
    "societe": "Le Marin",
    "rue": "13 rue du Breil",
    "cp": 35063,
    "ville": "Rennes",
    "latitude": "48.0956",
    "longitude": "-1.6269600000000537",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "groupeparent": "Ouest-France",
    "nom": "Boucher",
    "prenom": "Jean-Paul",
    "photo": "",
    "description": "Le Marin est un journal hebdomadaire, spécialisé dans les informations maritimes, dont le siège est à Rennes. Il appartient au Groupe Ouest-France."
  },
  {
    "societe": "Produits de la Mer",
    "rue": "13 rue du Breil",
    "cp": 35063,
    "ville": "Rennes",
    "latitude": "48.0956",
    "longitude": "-1.6269600000000537",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "groupeparent": "Ouest-France",
    "nom": "Boucher",
    "prenom": "Jean-Paul",
    "photo": "",
    "description": "Les produits de la mer désignent les animaux ou plantes qui sont consommés par les êtres humains. Ils comprennent les animaux marins, comme les poissons, mammifères, fruits de mer, ainsi que les algues et plantes marines."
  },
  {
    "societe": "Chasse Marée",
    "rue": "45 Boulevard Camille Reaud",
    "cp": 29100,
    "ville": "Douarnenez",
    "latitude": "48.0948",
    "longitude": "-4.334730000000036",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "groupeparent": "Ouest-France",
    "nom": "Boucher",
    "prenom": "Jean-Paul",
    "photo": "",
    "description": "Chasse-Marée est un magazine français qui paraît neuf fois par an, et une maison d'édition, créé en 1981 par la société coopérative ouvrière de production Le Chasse-Marée à Douarnenez."
  },
  {
    "societe": "Voiles et Voiliers",
    "rue": "13 rue du Breil",
    "cp": 35063,
    "ville": "Rennes",
    "latitude": "48.0956",
    "longitude": "-1.6269600000000537",
    "typeBatiment": "Rédaction",
    "photoBâtiment": "",
    "groupeparent": "Ouest-France",
    "nom": "Boucher",
    "prenom": "Jean-Paul",
    "photo": "",
    "description": "Créé en 1971, Voiles et Voiliers est un magazine mensuel français consacré à la voile sportive et de plaisance. Le magazine édite également des numéros hors-série et une collection d'ouvrages consacrés à la voile."
  },
  {
    "societe": "Edilarge",
    "rue": "13 rue du Breil",
    "cp": 35063,
    "ville": "Rennes",
    "latitude": "48.0956",
    "longitude": "-1.6269600000000537",
    "typeBatiment": "Edition de livres",
    "photoBâtiment": "",
    "groupeparent": "Ouest-France",
    "nom": "Boucher",
    "prenom": "Jean-Paul",
    "photo": "",
    "description": "Edition de livres.Depuis plus de quarante ans, les éditions Ouest-France s’imposent comme l’éditeur des régions.\nLoin de se limiter au grand ouest, \nelles participent activement à la mise en valeur\n du patrimoine culturel, local, régional et national.\n Du tourisme à l’histoire en passant par les arts,\n la peinture mais aussi les thématiques pratiques,\n 150 nouveautés sont publiées par an.\n Presque une trentaine de beaux-livres viennent enrichir\n chaque année un catalogue de 1800 titres et de\n 2000 auteurs tous spécialistes dans leurs domaines .\nRigueur de l’information et qualité de l’iconographie."
  }
 ]

 export default DATA;